project:
  type: website
  output-dir: docs
  render:
    - sesion1.qmd
    - about.qmd

website:
  title: "Curso R"
  navbar:
    right:
      - text: "Acerca del curso"
        href: about.html
      - text: "Sesión 1"
        href: sesion1.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
