project:
  type: website
  output-dir: docs
  render:
    - about.qmd
    - sesion1.qmd
    - sesion2.qmd
    - sesion3.qmd
    - sesion4.qmd

website:
  title: "La Datafora"
  navbar:
    left:
      - text: "Inicio"
        file: about.qmd
      - text: "Curso R"
        menu:
          - text: "Sesi贸n 1"
            file: sesion1.qmd
          - text: "Sesi贸n 2"
            file: sesion2.qmd
          - text: "Sesi贸n 3"
            file: sesion3.qmd
          - text: "Sesi贸n 4"
            file: sesion4.qmd
      - text: "Libro"
        file: rparaelanalisisdedatos/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
